language: ruby
cache: bundler
rvm:
  - "2.2"
  - "2.1"
  - "2.0"
before_install: gem install bundler -v "~> 1.2.0"
bundler_args: --without doc release

addons:
  code_climate:
    repo_token: 8f54d1653994973b85deca4c981fb8b03fbd25616e6f7c12f6728cbf3acf48bd
